spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true